### ISSUE TITLE
Mixin support

### ISSUE THREAD

**Issue by MatiasOlivera** [se-panfilov/vue-notifications#122]
Hi, I would like to be able to **reuse certain notifications through mixins**.

Are you planning to add this functionality in the near future? Right now, this doesn't work..

---

_CloseConfirmationMixin.js_
```javascript
export default {
    notifications: {
        closeConfimation:  {
           title: 'Foo',
           message: 'Bar',
           type: 'question', // <-- izitoast's type
           buttons: [ ... ] // <-- izitoast's config
       }
   }
}
```

_MyComponent.vue_
```vue
<template>
    <h1>Example</h1>
</template>

<script>
import CloseConfirmationMixin from './CloseConfirmationMixin.js'

export default {
    mixins: [ CloseConfirmationMixin ],
    methods: {
        close() {
            // some code
            this.closeConfimation(); // <-- Here throws an exception
        }
    }
}
</script>
```

_The exception_
`[Vue warn]: Error in event handler for "close": "TypeError: this.closeConfimation is not a function"`

---

**Dependencies**
```json
{
        "izitoast": "^1.3.0",
        "vue": "^2.5.7",
        "vue-notifications": "^0.9.0"
}
```

**Comment by se-panfilov** [comment]
@MatiasOlivera Hello and thanks for using `vue-notifications` ))

Honestly - no. `vue-notifications` is working via mixins itself, so I don't want to overcomplicate library.

I think if you want to create a reusable notification, you could do something like this:

CloseConfirmation.js

```js
export notifications: {
    closeConfimation:  {
      title: 'Foo',
      message: 'Bar',
      type: 'question', // <-- izitoast's type
      buttons: [ ... ] // <-- izitoast's config
    }
}
```

MyComponent.vue

```vue
<template>
    <h1>Example</h1>
</template>

<script>
import { notifications } from './CloseConfirmation.js'

export default {
    notifications: notifications,
    methods: {
        close() {
            // some code
            this.closeConfimation();
        }
    }
}
</script>
```

P.S. TBH - I didn't check this code, but I think it will works

**Comment by se-panfilov** [comment]
@MatiasOlivera I've closed the issue, but if you would have further questions - don't hesitate to ask
