### ISSUE TITLE
how to change the theme 

### ISSUE THREAD

**Issue by mrsai** [se-panfilov/vue-notifications#171]
how to change the theme ?

**Comment by M-Abdullahi** [comment]
This library is used as a 'building block' for other notification libraries that you might use in your application and doesn't come with styling. 
For example, You can use this library + izitoast. You style the notification using izitoast css, not using vue-notifications.

**Comment by se-panfilov** [comment]
@M-Abdullahi Thanks, indeed:
You should style minitiastr, izitoast or any other library that you use with vue-notifications
