### ISSUE TITLE
Demo or Screenshot ?

### ISSUE THREAD

**Issue by Jielde** [se-panfilov/vue-notifications#19]
Hi,

thank you for vue-notifications.
Please, can you provide a demo or screenshot?

Thx

**Comment by se-panfilov** [comment]
@Jielde Hey, sure.

First of all demos aren't ready (haven't time right now), but you can find something here:
https://se-panfilov.github.io/vue-notifications/

P.S. keep in mind that look and feel of demos was built with [mini-toastr](https://github.com/se-panfilov/mini-toastr)

**Comment by se-panfilov** [comment]
@Jielde Hey. Just FYI - starting from [v0.9.0](https://github.com/se-panfilov/vue-notifications/releases/tag/v0.9.0), we have [examples](https://github.com/se-panfilov/vue-notifications/tree/master/examples), [docs](https://se-panfilov.github.io/vue-notifications/docs/html/index.html) and [demos](https://se-panfilov.github.io/vue-notifications)
