### ISSUE TITLE
No Issue, just an Question

### ISSUE THREAD

**Issue by digitalit** [se-panfilov/vue-notifications#22]
Hi Sergey,

I use your miniToastr, this was the only toaster i could trigger from and Vuex action.

Two questions:

1. can i modify the toast to add icons and so on?
2. what do i gain by using this vue-notifications?

Thank you.

**Comment by se-panfilov** [comment]
@digitalit Hi and thank you for you interest

> 1. can i modify the toast to add icons and so on?

Basically `vue-notification` doesn't contains any "toast" itself =)

`vue-notification` - it's just an abstract layer between you app and any other "toast-lib".

I've implement [mini-toastr](https://github.com/se-panfilov/mini-toastr) lib that can be used together with `vue-notifications` (or without it, just as plain old-fashioned lib). And yeah, you can modify `mini-toastr` as you wish - via css or js (it use js-based config).

Or you can use any other "toaster-lib" with `vue-notifications`.

> 2. what do i gain by using this vue-notifications?

The goals of `vue-notification`:

  1. Let you include any toast library and switch it to another later if you want without pain;
  2. Keep all possible messages for each page in one place;

Workflow:

1. once you can map `vue-notifications` with any toaster library. Just to say to `vue-notifications` that in case of "error message" it has to call `yourToastr.error()`.  [[more info](https://github.com/se-panfilov/vue-notifications#setup-and-configuration)]

Basically in case of change toaster library you would just change this binding without need to go across all the project trying to find all methods like `yourToastr.error()`, `yourToastr.info()`, etc. 
Basically you can even replace console calls with `vue-notifications`

2. After that you can define on the page where you will need any kind of messages your notification's block:

```javascript
notifications: {
      someMsg: {
        type: 'error',
        message: 'This is my message'
      }
```

The goal here is to describe all possible messages for this page in one place.
And after that you would be able to call methods like `someMsg` (names same as top-level keys in `notifications` block)


So at the end it will be looking like this:

```javascript
export default {
    name: 'EmailView',
    data () {
      return {}
    },
    notifications: {
      emailTakenMsg: {
        type: 'error',
        message () {
          return this.i18n('some.internationalization')
        }
      },
      unknownError: {
        type: 'error',
        message: 'Some unknown error'
      }
    },
    methods: {
      checkEmail () {
        email.find({... }).then(this.isEmailAlreadyExist, this.isEmailNotExist)
      },
      isEmailNotExist ({ status, message }) {
        return this.unknownError({ debugMsg: message })
      },
      isEmailAlreadyExist (r) {
        this.emailTakenMsg()
      }
    }
  }
```

**Comment by digitalit** [comment]
Thank you,

I think i will stick with only miniToastr, it woks fine.

Is it possible to ad miniToastr globally so i dont have to ad it in every Vue component i wish to use it in?

Also, can i ad icons or html to miniToastr?

**Comment by se-panfilov** [comment]
@digitalit Hey, Sure ))

So, basically `miniToastr` it's a kind of old-school lib, so it's just can be access globally via `miniToastr` var (i.g. `window.miniToastr`).

So you can do `miniToastr.init()` in your main file and use it in any component. 
But perhaps the idea of adding it to each component not so bad, cause everyone hate use globals... but it's up to you

About Icons.
It was possible before, and I've implement it in more easier way.
Now you can bind your icons to toastr basically like this:

```javascript
miniToastr.setIcon('error', 'i', {'class': 'fa fa-warning'})
miniToastr.setIcon('warn', 'img', {src: 'assets/img/demo-warn.png', style: 'vertical-align: bottom;'})
``` 
(more info in readme)

You're able to use smth like `font-awesome`, or pure images as well.

So, all this in [v0.6.3](https://github.com/se-panfilov/mini-toastr/releases/tag/v0.6.3)
