### ISSUE TITLE
firefox watch issue

### ISSUE THREAD

**Issue by andrzejskutela** [se-panfilov/vue-notifications#48]
Hello

I'm using the newest release 0.7.6 of VueNotifications along with MiniToastr 0.6.5 and Vue 2.2.6. In Firefox (52), after defining your notifications in your component, all of them are fired when the main component is mounted. This strange behavior doesn't occur in Chrome (57).

I started debugging the code and I found that here
```javascript
launchWatchableNotifications (vueApp, notifications) {
    if (!notifications) return
    Object.keys(notifications).forEach(name => {
      if (vueApp[name] && notifications[name].watch) {
        vueApp[name]()
      }
})
```

in Chrome notifications[name].watch is undefined and the code is not executed (expected behavior IMO). However, in Firefox it is a function, defined [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/watch)

In my mind the Chrome behavior is the correct one, you don't want to fire all your notifications simply because your application is mounted. Personally I would kill that whole block of code, but I'm sure there was a reason for putting it there in the first place. Can you please confirm or dismiss my thinking here and update the code if needed.

Let me know if you can't reproduce the behavior or if you need any code samples. To me it's a very visible issue, but on the other hand it makes me very suspicious about the fact that I couldn't find anything related on google.

Thanks

**Comment by gfauconnet** [comment]
I have the same problem. I preferred using "VueNotifications.error({message: 'Some Text'})" to bypass this bug in my component but it is less elegant...

**Comment by se-panfilov** [comment]
@andrzejskutela, @gfauconnet I've published v0.8.0 just now.

I believe that this bug should gone after update.
Please let me know about that.

P.S. And thanks for a feedback guys

**Comment by se-panfilov** [comment]
Also `vue-notifications` now just `2.37 KB`

**Comment by gfauconnet** [comment]
It's ok for me ! Thanks for your work

**Comment by se-panfilov** [comment]
@gfauconnet Welcome! 👍  So I'm closing this issue
