### ISSUE TITLE
Types support

### ISSUE THREAD

**Issue by arthurvasconcelos** [se-panfilov/vue-notifications#69]
It is any plan on typescript support?

**Comment by se-panfilov** [comment]
@arthurvasconcelos Yeah. I want to add types in the next release.

I never did that before so, that's the problem. I mean I have to learn things first so be patient )) Or... PRs are welcome.

**Comment by arthurvasconcelos** [comment]
@se-panfilov cool! I will give a better reading to the lib code and try to implement typings! 😄 If successful I will make a PR.

**Comment by jalcine** [comment]
Hey, just revisiting this issue. TypeScript compatibility is a bit of a blocker for me. I can try looking into this; just would need some sense on how to handle things like the automatic injection of methods into components (TypeScript doesn't like that too much).

**Comment by se-panfilov** [comment]
Done in v1.0.0
