### ISSUE TITLE
can't work with mixins option

### ISSUE THREAD

**Issue by constantank** [se-panfilov/vue-notifications#70]
import mixin from './base'
import notifications from "../../../plugins/notification";

export default {
  mixins: [mixin],
  notifications
}

in .base.js , this.showOpenGraphSuccess() throw error: _this2.showOpenGraphSuccess is not a function

**Comment by se-panfilov** [comment]
@constantank To be honest I didn't catch what are you trying to do.

I guess `import notifications from "../../../plugins/notification";` should be `import VueNotifications from 'vue-notifications'`? (at least `notification` !== `vue-notifications`)

Can you provide a bit more clear example?
