### ISSUE TITLE
ReferenceError with mini-toastr v0.7.0

### ISSUE THREAD

**Issue by xidedix** [se-panfilov/vue-notifications#73]
looks like `vue-notifications` are broken with `mini-toastr v0.7.0` (v0.6.6 works fine)
`ReferenceError: CLASSES is not defined`
`ReferenceError: WARNING_CLASS is not defined`
or am I missing something here?

**Comment by se-panfilov** [comment]
Fixed in `mini-toastr` v0.7.2
